#!/usr/bin/env bash
# Post-quantum Panel<->Node tunnel: WireGuard + Rosenpass.
# User-level: key generation + config generation. Generates vpn/up.sh
# (the privileged sudo step that brings the tunnel up).
# Run on BOTH servers.
set -euo pipefail

cd "$(dirname "$0")"

# Refuse root: keygen and config generation are user-level.
if [[ "$(id -u)" -eq 0 ]]; then
  echo "error: refusing to run as root; run as your normal user" >&2
  exit 1
fi

for dep in ip wg; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    echo "error: missing dependency: $dep" >&2
    exit 1
  fi
done
if ! command -v rp >/dev/null 2>&1 && ! command -v rosenpass >/dev/null 2>&1; then
  echo "error: rosenpass (binary 'rp' or 'rosenpass') is required but not found" >&2
  echo "install hint: https://rosenpass.eu/docs/rosenpass-tool/guides/linux/" >&2
  exit 1
fi

read -r -p "Role (panel|node) [panel]: " ROLE
ROLE="${ROLE:-panel}"
case "$ROLE" in
  panel) OTHER_ROLE="node" ;;
  node)  OTHER_ROLE="panel" ;;
  *) echo "error: role must be panel or node" >&2; exit 1 ;;
esac

# This server's public IP/domain (panel uses it to listen; node uses the panel's).
read -r -p "This server's public IP/domain: " PUBLIC_IP
while [[ -z "${PUBLIC_IP:-}" ]]; do
  read -r -p "This server's public IP/domain: " PUBLIC_IP
done

# Peer's public IP/domain (node needs it as the endpoint; panel needs it for firewall).
read -r -p "Peer's public IP/domain: " PEER_IP
while [[ -z "${PEER_IP:-}" ]]; do
  read -r -p "Peer's public IP/domain: " PEER_IP
done

read -r -p "Tunnel network [10.99.0.0/24]: " TUNNEL_NET
TUNNEL_NET="${TUNNEL_NET:-10.99.0.0/24}"
NETADDR="${TUNNEL_NET%/*}"
CIDR="${TUNNEL_NET#*/}"
TUNNEL_IP="${NETADDR%.*}.$( [[ "$ROLE" == "panel" ]] && echo 1 || echo 2 )"

read -r -p "Rosenpass UDP port [9999]: " RP_PORT
RP_PORT="${RP_PORT:-9999}"
WG_PORT=$((RP_PORT + 1))

echo
echo "==> generating Rosenpass key pair for this server (vpn/keys/)"
mkdir -p keys
rp genkey "keys/${ROLE}.rosenpass-secret"
rp pubkey "keys/${ROLE}.rosenpass-secret" "keys/${ROLE}.rosenpass-public"

if [[ "$ROLE" == "panel" ]]; then
  RP_CMD="rp exchange keys/${ROLE}.rosenpass-secret \\
  dev rosenpass0 \\
  listen ${PUBLIC_IP}:${RP_PORT} \\
  peer keys/${OTHER_ROLE}.rosenpass-public \\
  allowed-ips ${TUNNEL_NET}"
else
  RP_CMD="rp exchange keys/${ROLE}.rosenpass-secret \\
  dev rosenpass0 \\
  peer keys/${OTHER_ROLE}.rosenpass-public \\
  endpoint ${PEER_IP}:${RP_PORT} \\
  allowed-ips ${TUNNEL_NET}"
fi

cat > up.sh <<EOF
#!/usr/bin/env bash
# Generated by vpn/install.sh — run with sudo on this server.
set -euo pipefail
cd "\$(dirname "\$0")"

${RP_CMD}

ip a add ${TUNNEL_IP}/${CIDR} dev rosenpass0 2>/dev/null || true
ip route add ${TUNNEL_NET} dev rosenpass0 2>/dev/null || true
EOF
chmod +x up.sh

cat > down.sh <<'EOF'
#!/usr/bin/env bash
# Generated by vpn/install.sh — run with sudo to tear down the tunnel.
set -euo pipefail
ip link del rosenpass0 2>/dev/null || true
EOF
chmod +x down.sh

echo
echo "==> next steps"
echo "1. Copy this server's public key to the peer:"
echo "   scp -r keys/${ROLE}.rosenpass-public user@${PEER_IP}:<repo>/vpn/keys/"
echo "2. Run this installer on the peer (role=${OTHER_ROLE}), then copy its public"
echo "   key back here the same way. Both sides need both -public dirs in vpn/keys/."
echo "3. Bring the tunnel up on both servers:  sudo ./up.sh"
echo "4. Firewall: open UDP ${RP_PORT} (Rosenpass) and ${WG_PORT} (WireGuard)"
echo "   to ${PEER_IP} only."
echo "5. Verify:  wg show rosenpass0 preshared-keys   (PSK rotates every ~2 min)"
echo "   and:      ping ${TUNNEL_IP}"
echo
echo "Panel setup: add the node with address=${TUNNEL_IP} (the tunnel IP);"
echo "NODE_PORT no longer needs to be exposed publicly."
